import Modal from "@/components/Modal";
import { auth } from "@/lib/auth";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import ClientLayout from "./client/layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <SessionProvider session={session} refetchOnWindowFocus={false}>
      <ClientLayout>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Toaster />
            <Modal />
          </body>
        </html>
      </ClientLayout>
    </SessionProvider>
  );
}
